services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - ecom-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ecom-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=elk-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false          # for dev
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ecom-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 15s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - SERVER_NAME=kibana
    ports:
      - "5601:5601"
    networks:
      - ecom-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:5601/api/status | grep -q '\"overall\":{\"level\":\"available\"'"]
      interval: 20s
      timeout: 10s
      retries: 10

  fluent-bit:
    image: fluent/fluent-bit:3.1
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    ports:
      - "24224:24224"
      - "24224:24224/udp"  
      - "2020:2020"
    networks:
      - ecom-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  jaeger:
      image: jaegertracing/all-in-one:1.76.0
      container_name: jaeger
      restart: unless-stopped
      environment:
        - COLLECTOR_OTLP_ENABLED=true
        - SPAN_STORAGE_TYPE=memory
        - MEMORY_MAX_TRACES=50000
      ports:
        - "16686:16686"
        - "4317:4317"
        - "4318:4318"
      healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://localhost:14269/"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - ecom-network

  discovery-service:
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
    environment:
      SERVER_PORT: 8761
    ports:
      - "8761:8761"
    networks:
      - ecom-network

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      SERVER_PORT: 8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_SERVICE_URL: discovery-service:8761
      JWT_SECRET: ${JWT_SECRET}
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: auth-service
    networks:
      - ecom-network

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      redis:
        condition: service_started
      jaeger:
        condition: service_started      
    environment:
      SERVER_PORT: 8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: product-service

    networks:
      - ecom-network

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      SERVER_PORT: 8002
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: order-service
    networks:
      - ecom-network

  inventory-service:
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      SERVER_PORT: 8003
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: inventory-service

    networks:
      - ecom-network

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      discovery-service:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      SERVER_PORT: 8004
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payment_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_SERVICE_URL: discovery-service:8761
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: payment-service

    networks:
      - ecom-network


  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    depends_on:
      discovery-service:
        condition: service_started
      fluent-bit:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVICE_URL: discovery-service:8761
      JAEGER_SERVICE_URL: jaeger:4318
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
        tag: api-gateway
    ports:
      - "8080:8080"
    networks:
      - ecom-network

volumes:
  pgdata:
  redis-data:
  esdata:

networks:
  ecom-network:
    driver: bridge