server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback/auth

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/fallback/product

        - id: admin-product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/admin/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminProductService
                fallbackUri: forward:/fallback/product

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/fallback/order

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryService
                fallbackUri: forward:/fallback/inventory

        - id: admin-inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/admin/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminInventoryService
                fallbackUri: forward:/fallback/inventory

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentService
                fallbackUri: forward:/fallback/payment

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cartService
                fallbackUri: forward:/fallback/cart

  reactor:
    context-propagation: auto
security:
  public-endpoints: /auth,/products,/payments/webhook

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL}/eureka

jwt:
  secret: ${JWT_SECRET}

management:
  tracing:
    sampling:
      probability: 1.0  #dev
  otlp:
    tracing:
      endpoint: http://${JAEGER_SERVICE_URL}/v1/traces


resilience4j:

  circuitbreaker:
    instances:

      authService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      productService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      adminProductService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      orderService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      inventoryService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      adminInventoryService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      paymentService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s

      cartService:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15s


  timelimiter:
    instances:

      authService:
        timeoutDuration: 5s

      productService:
        timeoutDuration: 5s

      adminProductService:
        timeoutDuration: 5s

      orderService:
        timeoutDuration: 5s

      inventoryService:
        timeoutDuration: 5s

      adminInventoryService:
        timeoutDuration: 5s

      paymentService:
        timeoutDuration: 5s

      cartService:
        timeoutDuration: 5s