server:
  port: 8001

spring:
  application:
    name: product-service

  datasource  :
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode:
        never
      data-locations:
        classpath:data.sql


  kafka:
    bootstrap-servers: localhost:9092

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka