server:
  port: ${SERVER_PORT:8001}

spring:
  application:
    name: product-service

  datasource  :
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  reactor:
    context-propagation: auto

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode:
        never
      data-locations:
        classpath:data.sql

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  cache:
    type: redis

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}


#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL}/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    export:
      otlp:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: false
  logging:
    export:
      otlp:
        enabled: false
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
    tracing:
      export:
        otlp:
          endpoint: http://${JAEGER_SERVICE_URL}/v1/traces
