server:
  port: ${SERVER_PORT:8005}

spring:
  application:
    name: cart-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVICE_URL}/eureka

